#!/usr/bin/env python3

import sys
import helpers
import os
from analyzer import Analyzer # imports a class Analyzer from a module called analyzer
from termcolor import colored # import a function colored from a module termcolor
# TODO
def main():
# accepts one and only one command-line argument, the screen name for a user on Twitter,
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
# queries Twitter’s API for a user’s most recent 50 tweets,
    screen_name = sys.argv[1].lstrip('@')
    tweets = helpers.get_user_timeline(screen_name, 50)
# analyzes the sentiment of each of those tweets, and

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    analyzer = Analyzer(positives, negatives) # instantiate analyzer
    
    if tweets == None:
        sys.exit("Error reading tweet's")
    
# outputs each tweet’s score and text, colored in green if positive, red if negative, and yellow otherwise.
    # analyze word such us in smile <--
    for i in tweets:
        score = analyzer.analyze(i)
        if score > 0.0:
            print(colored("{} {}".format(score, i), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, i), "red"))
        else:
            print(colored("{} {}".format(score, i), "yellow"))

if __name__ == "__main__":
    main()    

## export API_KEY=iRchR719VUlKFiHlaohfIo6sX
## export API_SECRET=w7HO9piCd7sN8TCKIUBmzxZiHNu8yHW1co8MceXgHU8CM680Ix